services:
  - type: web
    name: ww-booking-cal
    runtime: node
    buildCommand: npm install --include=dev && cd client && npm install --include=dev && cd ../server && npm install --include=dev && cd .. && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ACCESS_KEY
        sync: false
